### ISSUE TITLE
not letting me inject png files 

### ISSUE THREAD

**Issue by JudahMourning** [OpenNaja/cobra-tools#307] opened 2023-02-16 19:53 UTC
**Describe the bug**

**To Reproduce**
1. Go to open once you get your animal and remake a the png
2. Click on inject'
4. See error and see no pngs showing

**Expected behavior**
once I tried to inject my PNG it didn't work.

**Screenshots**
![Screenshot 2023-02-16 144716](https://user-images.githubusercontent.com/40230259/219471392-4835e5d2-d90e-478a-9ce0-9a6f57deaf99.png)
**Version Info:**
 - Python Version: [e.g. 3.7.2]
 - Blender Version: [e.g. 2.92]

**Comment by HENDRIX-ZT2** [comment] 2023-02-26 17:15
Duplicate of #214, #305

**Closed by HENDRIX-ZT2** 2023-02-26 17:15 UTC
