### ISSUE TITLE
OVL - Support Planet Coaster

### ISSUE THREAD

**Issue by PxpUii** [OpenNaja/cobra-tools#138] opened 2021-10-23 13:13 UTC
I want the program to support the .GFX file type. I want to change the font. I can export it but I can't import it. Please make the program support .GFX files from Planet Coas game.

**Comment by ilodev** [comment] 2021-11-22 08:28
Done, give it a try with the latest version and see if we can close this one.

**Comment by HENDRIX-ZT2** [comment] 2021-12-12 23:34
Right now the problem is that we don't support saving for pc as we don't have the generated constants file integrated. Once we have that, it should work.

**Comment by Poslovitch** [comment] 2022-04-19 09:28
How have you generated the existing constants files for PZ & JWE? I might be able to work on this for PC.

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 12:28
> How have you generated the existing constants files for PZ & JWE? I might be able to work on this for PC.

In the OVL tool, Util > Generate Hash Table. Select Planet Coaster's game root folder in the popup.

This will dump the constants file and the hash table in the `hashes` subfolder of cobra-tools.
Rename them to constants_pc.py and ovldata-pc.txt, respectively and upload here.

**Comment by Poslovitch** [comment] 2022-04-19 13:59
Is there a way to modify the output file? I'm running into this error:
`[Errno 2] No such file or directory: 'C:\\WINDOWS\\system32\\hashes\\Planet Coaster.txt'`

And, well, I'd like to avoid writing anything into my system32.

Full logs attached
[planco_hash_log.zip](https://github.com/OpenNaja/cobra-tools/files/8513610/planco_hash_log.zip)

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 14:02
> Is there a way to modify the output file? I'm running into this error: `[Errno 2] No such file or directory: 'C:\\WINDOWS\\system32\\hashes\\Planet Coaster.txt'`
> 
> And, well, I'd like to avoid writing anything into my system32.
> 
> Full logs attached [planco_hash_log.zip](https://github.com/OpenNaja/cobra-tools/files/8513610/planco_hash_log.zip)

Thanks! Surely. It's based on the assumption that the user runs it by double clicking the py file, so that the CWD is the tools folder. I'll fix that.

**Comment by Poslovitch** [comment] 2022-04-19 14:07
Well, I was double-clicking on the py file, so maybe that's why it was assuming CWD is system32 ? When I run the py file from a shell in the tools folder, it seems to use the tools folder as the "default" one.

However, I still run in the big error message you can find in my logs: [array of files] caused error!

So, `Planet Coaster.txt` is empty. However `constants_Planet Coaster.py` is not. See attached:
[constants_Planet Coaster.zip](https://github.com/OpenNaja/cobra-tools/files/8513669/constants_Planet.Coaster.zip)

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 14:21
There seems to be a bug in addition that causes the tools to crash.

**Comment by Poslovitch** [comment] 2022-04-19 14:23
Well then, if you need some to do tests, I'm at your disposal. I'm really interested in seeing these amazing tools work smoothly for PlanCo too 😉

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 14:48
> Well then, if you need some to do tests, I'm at your disposal. I'm really interested in seeing these amazing tools work smoothly for PlanCo too 😉

I've fixed the bugs, you can now grab the https://github.com/OpenNaja/cobra-tools/tree/refactor-codegen branch, run again and upload the results.

**Comment by Poslovitch** [comment] 2022-04-19 14:57
The CWD fix works like a charm!

There are far less errors now, but some OVLs are still erroring (`Init.ovl` are seemingly all erroring? Yesterday I couldn't get to unpack a single one, each one of them was failing with the same `unpack requires a buffer of 4 bytes`).

Here are the logs, have some fun 😁 :
[planco_hashes_log_refactor.zip](https://github.com/OpenNaja/cobra-tools/files/8514107/planco_hashes_log_refactor.zip)

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 14:59
> The CWD fix works like a charm!
> 
> There are far less errors now, but some OVLs are still erroring (`Init.ovl` are seemingly all erroring? Yesterday I couldn't get to unpack a single one, each one of them was failing with the same `unpack requires a buffer of 4 bytes` error).
> 
> Here are the logs, have some fun 😁 : [planco_hashes_log_refactor.zip](https://github.com/OpenNaja/cobra-tools/files/8514107/planco_hashes_log_refactor.zip)

Great!
Can you upload one of the init ovls? I think they may be encrypted.
Also, If you upload the constants and hashes files, I should be able to get saving support going

**Comment by Poslovitch** [comment] 2022-04-19 15:03
Current constants and hashes files : [hashes_and_constants.zip](https://github.com/OpenNaja/cobra-tools/files/8514151/hashes_and_constants.zip)
The Init OVL from Content0: [Content0_Init.zip](https://github.com/OpenNaja/cobra-tools/files/8514159/Content0_Init.zip)

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 15:04
> Current constants and hashes files : [hashes_and_constants.zip](https://github.com/OpenNaja/cobra-tools/files/8514151/hashes_and_constants.zip) The Init OVL from Content0: [Content0_Init.zip](https://github.com/OpenNaja/cobra-tools/files/8514159/Content0_Init.zip)

Yup, encrypted, no change reading those.

**Comment by Poslovitch** [comment] 2022-04-19 15:06
Kay. So I'll have to figure out how content packs work for PlanCo without having access to those. That's tough.

**Comment by HENDRIX-ZT2** [comment] 2022-04-19 15:28
> Kay. So I'll have to figure out how content packs work for PlanCo without having access to those. That's tough.

There may be some help for you at https://discord.gg/CVKkFaXw
In any case, the refactor branch is now able to save PC ovls!

**Comment by HENDRIX-ZT2** [comment] 2022-08-07 12:23
The only thing left is support for sorting buffers for saving

**Comment by ilodev** [comment] 2022-08-07 16:27
@Poslovitch if we assume content packs are like with other games, you can probably extrapolate from DLA, PZ or JWE assuming what is in init\ . I'm pretty sure it is quite straight forward since Init\ is really engine based, there might be a Lua script + asset package definitions, maybe some other types of files that you probably won't need.

**Comment by HENDRIX-ZT2** [comment] 2022-09-05 17:39
Buffer logic is fixed!

**Comment by HENDRIX-ZT2** [comment] 2022-09-06 13:03
Buffer logic works, tex format is functional again. General issue is resolved, so closed.

**Closed by HENDRIX-ZT2** 2022-09-06 13:03 UTC
Labels: enhancement
