### ISSUE TITLE
Unable to inject PNG files in cobra master tools. How to fix it. Becase PNG format is not supported?

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#215] opened 2022-07-06 04:12 UTC
I am trying to change a dinosaur colour in JWE2 game. Using the Cobra Master tool, I unpacked one of the dinosaur from the game and changed the dinosaur colour in PNG base file. But when I try to inject the file, PNG is not supported during inject. Please assist how to fix this issue.

**Comment by HENDRIX-ZT2** [comment] 2022-07-09 07:55
Duplicate of #214
Closed

**Closed** 2022-07-09 07:55 UTC
