### ISSUE TITLE
RCT3 OVL support

### ISSUE THREAD

**Issue by RobbinBob** [OpenNaja/cobra-tools#376] opened 2024-03-19 16:30 UTC
Would be nice for this to work with rollercoaster tycoon 3's ovl files if its possible

**Comment by HENDRIX-ZT2** [comment] 2024-03-20 20:23
The older OVL format is totally different. Various tools exist for it.
Duplicate of #300, closed.

**Closed by HENDRIX-ZT2** 2024-03-20 20:23 UTC
