### ISSUE TITLE
Jurassic World Evolution 2 OVL Archive editor not supporting PNG

### ISSUE THREAD

**Issue by BabaZabava** [OpenNaja/cobra-tools#305] opened 2023-02-14 20:41 UTC
I'm trying to help my son edit dinosaur textures in JWE2.

Followed a youtube tutorial  installed python, redistributables, and everything works up to the point where i extract a dinosaur OVL, and edit and save the PNG file. 

When I want to inject the edited PNG back into the  OVL it doesn't show up the selection, PNG is not listed in the supported filetypes, drag and drop doesn't work either.

Any idea why that might be happening?

Thanks!

**Comment by HENDRIX-ZT2** [comment] 2023-02-15 08:28
You have to inject back the tex file, not the png file. The tex file automatically locates all the required png files on injection.

**Comment by HENDRIX-ZT2** [comment] 2023-02-15 17:35
Also duplicate of #214

**Closed** 2023-02-26 17:15 UTC
