### ISSUE TITLE
Support for Planet Coaster 2?

### ISSUE THREAD

**Issue by Narayanna** [OpenNaja/cobra-tools#404] opened 2024-11-19 09:56 UTC
Hello, will there be support for Planet Coaster 2?
Actually, the latest version opens the files, but the content of the text files is incorrect and incomplete. So I think a fix is needed.

This is the archive file containing the game's language files.
https://www.mediafire.com/file/wdvr23y4v3wm5th/Loc.ovl/file

**Comment by HENDRIX-ZT2** [comment] 2024-11-19 15:54
How are the contents incomplete? Please provide a sample txt file and the tool's log file.

**Comment by Narayanna** [comment] 2024-11-20 14:44
> How are the contents incomplete? Please provide a sample txt file and the tool's log file.

I'm sorry, I don't know where the vehicle's log file is. I uploaded some sample files, the text files are missing lines, so there is no complete content.https://www.mediafire.com/file/qbj8oqwisac9b7u/PC2.rar/file

In Jurassic World Evolution 2 the texts were in UTF-8 format and there was no problem, in this game the texts are in ANSI format, could this have something to do with it?

**Comment by HENDRIX-ZT2** [comment] 2024-11-20 16:19
> > How are the contents incomplete? Please provide a sample txt file and the tool's log file.
> 
> I'm sorry, I don't know where the vehicle's log file is. I uploaded some sample files, the text files are missing lines, so there is no complete content. https://www.mediafire.com/file/qbj8oqwisac9b7u/PC2.rar/file

> 
> In Jurassic World Evolution 2 the texts were in UTF-8 format and there was no problem, in this game the texts are in ANSI format, could this have something to do with it?

I can't reproduce the error with current master, so without you providing a log file from the tools folder, I can only close this issue.
[accept.txt](https://github.com/user-attachments/files/17833632/accept.txt)
[acceleration_g.txt](https://github.com/user-attachments/files/17833633/acceleration_g.txt)

**Closed by HENDRIX-ZT2** 2024-11-20 16:19 UTC
Labels: invalid

**Comment by Narayanna** [comment] 2024-11-20 16:36
> I can't reproduce the error with current master, so without you providing a log file from the tools folder, I can only close this issue. [accept.txt](https://github.com/user-attachments/files/17833632/accept.txt) [acceleration_g.txt](https://github.com/user-attachments/files/17833633/acceleration_g.txt)

[ovl_tool_gui.log](https://github.com/user-attachments/files/17833790/ovl_tool_gui.log)

I found a diary file, is that what this is?

**Comment by HENDRIX-ZT2** [comment] 2024-11-20 16:36
Thanks!
You don't have the game selected in the installed games dropdown, so you must change the game version in the top right manually to PC2 before trying to open an OVL file. Frontier have changed the OVL format without changing the version number...
```
DEBUG | Setting OVL Game to Unknown Game
INFO | Setting OVL version to Unknown Game
DEBUG | Loading threaded True
INFO | Loading Loc.ovl
INFO | Game: Planet Zoo```

**Comment by Narayanna** [comment] 2024-11-20 16:40
Thanks, but there's no Planet Coaster 2 option here. Which one should I choose?

![PC2](https://github.com/user-attachments/assets/adf18ea8-888c-4381-9f05-b24712eb5fb7)

**Comment by HENDRIX-ZT2** [comment] 2024-11-20 16:45
Your tools are severely outdated, see the version number. You need to use: https://github.com/OpenNaja/cobra-tools/archive/refs/heads/master.zip
